---
- hosts: localhost # This means the playbook runs on the Ansible controller itself, assuming it's a Windows machine with IIS.
  tasks:
    - name: Stop an application pool
      win_iis_webapppool:
          name: AppPool
          state: stopped
      # This task is correct for stopping an IIS application pool.

    - name: Backup Web Config
      win_copy:
          src: D:\WSGC\UIScom\web.config
          dest: D:\Temp\UIScom\web.config
      # This task copies the web.config file.
      # QUESTION: Does D:\Temp\UIScom\ already exist, or does win_copy create it?
      # win_copy will create the D:\Temp\UIScom directory if it doesn't exist.

    - name: Clean Home Directory
      win_file:
          path: D:\WSGC\UIScom
          state: absent
      # This task will DELETE the entire D:\WSGC\UIScom directory and its contents.
      # WARNING: This means the 'web.config' that was just backed up will also be deleted if it was backed up into a subfolder of D:\WSGC\UIScom.
      # HOWEVER, in your backup step, you're backing up to D:\Temp\UIScom\web.config, which is outside D:\WSGC\UIScom. So this is fine.
      # This is an aggressive clean. Make sure this is desired behavior.

    - name: Deploy new Build
      win_copy:
          src: D:\WSGC\UIScom # This 'src' path is problematic.
          dest: D:\WSGC\UIScom
      # This task has an issue:
      # - 'src: D:\WSGC\UIScom' implies that the source of the new build is already on the *target machine* at D:\WSGC\UIScom.
      #   But you just deleted this directory in the previous step (`state: absent`).
      # - If the build is on the *Ansible controller* (the 'localhost' in this case), then 'src' should point to a path on the controller
      #   (e.g., 'src: C:\AnsibleBuilds\UIScom').
      # - If 'D:\WSGC\UIScom' on the *controller* contains the build, and you want to copy it to the *target* D:\WSGC\UIScom, this syntax is still incorrect
      #   because `win_copy` implies copying from controller to target. But here, target is also localhost.
      # - To deploy a "new build" from the Ansible controller to the same 'localhost' target, the 'src' should be a path on the controller
      #   where the new build resides (e.g., 'src: C:\path\to\your\new\build_files\UIScom').
      # - If 'D:\WSGC\UIScom' is intended to be the source path on the *remote* server, you would need `remote_src: yes`, but since you deleted it,
      #   and this is `localhost`, it doesn't make sense as a source for a new build.

    - name: Restore Web config
      win_copy:
          src: D:\Temp\UIScom\web.config
          dest: D:\WSGC\UIScom\web.config
      # This task is correct assuming the `D:\WSGC\UIScom` directory has been re-created by the 'Deploy new Build' step.
      # The `win_copy` module will create the D:\WSGC\UIScom directory if it doesn't exist when writing to D:\WSGC\UIScom\web.config.

    - name: Start an application pool
      win_iis_webapppool:
          name: AppPool
          state: started
      # This task is correct for starting the application pool.

    #name of 1212 - This is a comment, likely incomplete or a placeholder.

